language: cpp
dist: bionic
compiler: gcc

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qt5-default -y
 
addons:
 sonarcloud:
  organization: "genia10"
  token: $SONAR_TOKEN
 
before_install:
 - pip install --user cpp-coveralls
 
script:
 - qmake
 - make
 - ./tests/tests
 
after_success:
 - coveralls --root . -E ".*external.*" -E ".*tests.*"
 - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
 - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

notifications:
 email: false
